(()=>{'use strict';
const TIME_MS=5000,POINTS=10;
const questions=[{"id": 1, "full": "assets/full01.jpg", "zoom": "assets/q01.jpg", "width": 1046, "height": 717, "x": 673.5, "y": 445.5, "tolX": 93, "tolY": 61, "markSize": 16}, {"id": 2, "full": "assets/full02.jpg", "zoom": "assets/q02.jpg", "width": 1046, "height": 717, "x": 241.5, "y": 252.5, "tolX": 111, "tolY": 49, "markSize": 16}, {"id": 3, "full": "assets/full03.png", "zoom": "assets/q03.jpg", "width": 1046, "height": 717, "x": 945.0, "y": 329.0, "tolX": 62, "tolY": 45, "markSize": 16}, {"id": 4, "full": "assets/full04.png", "zoom": "assets/q04.png", "width": 1046, "height": 717, "x": 562.5, "y": 230.5, "tolX": 93, "tolY": 97, "markSize": 16}, {"id": 5, "full": "assets/full05.png", "zoom": "assets/q05.jpg", "width": 1046, "height": 717, "x": 308.0, "y": 614.0, "tolX": 76, "tolY": 59, "markSize": 16}, {"id": 6, "full": "assets/full06.png", "zoom": "assets/q06.png", "width": 1046, "height": 717, "x": 823.0, "y": 367.0, "tolX": 63, "tolY": 46, "markSize": 16}, {"id": 7, "full": "assets/full07.png", "zoom": "assets/q07.jpg", "width": 1046, "height": 717, "x": 274.0, "y": 259.5, "tolX": 62, "tolY": 45, "markSize": 16}, {"id": 8, "full": "assets/full08.png", "zoom": "assets/q08.jpg", "width": 1754, "height": 1240, "x": 1439.5, "y": 465.5, "tolX": 186, "tolY": 87, "markSize": 16}, {"id": 9, "full": "assets/full09.png", "zoom": "assets/q09.png", "width": 1046, "height": 717, "x": 863.0, "y": 535.0, "tolX": 76, "tolY": 75, "markSize": 16}, {"id": 10, "full": "assets/full10.png", "zoom": "assets/q10.png", "width": 1046, "height": 717, "x": 270.5, "y": 299.0, "tolX": 47, "tolY": 45, "markSize": 16}];
const $=id=>document.getElementById(id);
const el={welcome:$('welcome'),game:$('game'),result:$('result'),form:$('startForm'),name:$('playerName'),progress:$('progress'),score:$('score'),target:$('target'),timeFill:$('timeFill'),imageBox:$('imageBox'),painting:$('painting'),mark:$('mark'),feedback:$('feedback'),home:$('homeBtn')};
let round=0,sequence=[],hits=0,correctTime=0,startedAt=0,player='',active=false,raf=0,nextTimer=0,sessionId='',currentQ=null;
const show=id=>{for(const p of [el.welcome,el.game,el.result])p.classList.toggle('hide',p.id!==id);window.scrollTo(0,0)};
const order=()=>{let arr=Array.from({length:questions.length},(_,i)=>i);for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr};
function start(e){e.preventDefault();player=el.name.value.trim().replace(/[<>]/g,'').slice(0,18);if(!player){alert('이름이나 별명을 입력해 주세요.');return}if(!document.getElementById('consent').checked)return;
 sequence=order();round=0;hits=0;correctTime=0;sessionId=(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random());show('game');load()}
function load(){clearTimeout(nextTimer);cancelAnimationFrame(raf);if(round>=questions.length){finish();return}active=false;const index=sequence[round];currentQ=questions[index];
 el.target.src=currentQ.zoom;el.painting.src=currentQ.full;el.progress.textContent=`${round+1} / ${questions.length}`;el.score.textContent=`${hits}개 맞힘`;el.mark.classList.add('hide');el.mark.classList.remove('wrong');el.feedback.textContent='그림 속 위치를 찾아 터치하세요!';
 const activate=()=>{startedAt=performance.now();active=true;tick()};
 if(el.painting.complete) activate(); else el.painting.onload=activate;
 updateMarkSize();}
function updateMarkSize(){if(!currentQ)return;el.mark.style.width=(currentQ.markSize||11)+'%';}
function tick(){if(!active)return;const remain=Math.max(0,TIME_MS-(performance.now()-startedAt));el.timeFill.style.width=(remain/TIME_MS*100)+'%';if(remain===0){answer(false,true);return}raf=requestAnimationFrame(tick)}
function answer(correct,timeout,x,y){if(!active)return;active=false;cancelAnimationFrame(raf);if(correct){hits++;correctTime+=Math.min(TIME_MS,performance.now()-startedAt);el.feedback.textContent='✅ 정답! +10점';el.mark.style.left=(x/currentQ.width*100)+'%';el.mark.style.top=(y/currentQ.height*100)+'%';el.mark.classList.remove('hide','wrong')}else{el.feedback.textContent=timeout?'⏰ 시간 초과!':'❌ 아쉬워요! 다음 문제로 넘어갑니다.';el.mark.style.left=(currentQ.x/currentQ.width*100)+'%';el.mark.style.top=(currentQ.y/currentQ.height*100)+'%';el.mark.classList.remove('hide');el.mark.classList.add('wrong')}round++;nextTimer=setTimeout(load,850)}
el.imageBox.addEventListener('click',e=>{if(!active||!currentQ)return;const r=el.painting.getBoundingClientRect();const x=(e.clientX-r.left)/r.width*currentQ.width,y=(e.clientY-r.top)/r.height*currentQ.height;const match=Math.abs(currentQ.x-x)<=currentQ.tolX&&Math.abs(currentQ.y-y)<=currentQ.tolY;answer(match,false,x,y)});
async function finish(){show('result');$('finalScore').textContent=hits;$('resultSummary').textContent=`${player}님, ${questions.length}문제 중 ${hits}문제를 맞혔습니다.`;
 const entry={sessionId,name:player,score:hits*POINTS,correct:hits,correctTimeMs:Math.round(correctTime),finishedAt:new Date().toISOString()};const url=(window.QUIZ_CONFIG||{}).submissionUrl;
 if(url){$('saveStatus').textContent='결과 전송 중입니다…';try{await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(entry)});$('saveStatus').textContent='결과를 전송했습니다. 네트워크 사정에 따라 반영 여부를 관리자에게 확인해 주세요.'}catch(e){$('saveStatus').textContent='⚠️ 전송에 실패했습니다. 전시장 담당자에게 알려 주세요.'}}else{let entries=[];try{entries=JSON.parse(localStorage.getItem('bruegel_demo_results')||'[]')}catch(e){}entries.push(entry);try{localStorage.setItem('bruegel_demo_results',JSON.stringify(entries))}catch(e){}$('saveStatus').textContent='⚠️ 시연 모드: 결과는 이 기기에만 저장됩니다. 전체 집계를 위해 관리자가 Google Sheets 연동을 설정해야 합니다.'}}
el.form.addEventListener('submit',start);el.home.addEventListener('click',()=>{el.name.value='';document.getElementById('consent').checked=false;show('welcome')});
})();
